dealershop/dealershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('', RedirectView.as_view(url='inventory/')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

dealershop/inventory/urls.py
from django.urls import path

from . import views

# added app namespace
app_name = 'inventory'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('fbv', views.fbv_view, name='fbv'),
    # path('car/', views.CarFormView.as_view(), name='car'),
    path('create_car/', views.CarCreateView.as_view(), name='car-create'),
    path('list_car/', views.CarListView.as_view(), name='car-list'),
    path('detail_car/<int:pk>', views.CarDetailView.as_view(), name='car-detail'),
    path('update_car/<int:pk>', views.CarUpdateView.as_view(), name='car-update'),
    path('delete_car/<int:pk>', views.CarDeleteView.as_view(), name='car-delete'),
]

dealershop/inventory/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    color = models.CharField(max_length=200)
    year = models.IntegerField(default=1900)

    def __str__(self):
        return f"{self.brand}_{self.model}_{self.color}_{self.year}"

    class Meta:
        ordering = ['-year']

class Inventory(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    number = models.IntegerField(default=1900)

dealershop/inventory/forms.py
from django import forms

class CarForm(forms.Form):
    brand = forms.CharField()
    model = forms.CharField()
    color = forms.CharField()
    year = forms.IntegerField()

    def do_action(self):
        # do any action
        print("do action!!")

dealershop/dealershop/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

# https://docs.djangoproject.com/en/4.1/topics/auth/default/#module-django.contrib.auth.forms
class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

dealershop/inventory/views.py
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def fbv_view(request):
    context = {
        "name": "Joon"
    }
    return render(request, 'inventory/fbv.html', context)

# class MainView(View):
#     def get(self, request):
#         # <view logic>
#         return HttpResponse('result')

class MainView(TemplateView):
    template_name = "inventory/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = "Joon"
        return context
    
from django.views.generic.edit import FormView
from inventory.forms import CarForm
from django.urls import reverse_lazy, reverse

class CarFormView(FormView):
    template_name = 'inventory/car_basic_form.html'
    form_class = CarForm
    # success_url = '/inventory'

    # # why can't we use reverse?
    # # because then reverse is called when the module is imported, before the urls have been loaded.
    # # class attributes are evaluated on import,
    # # success_url = reverse("inventory:main")
    # # Reverse_lazy is, as the name implies, a lazy implementation of the reverse URL resolver. Unlike the traditional reverse function, reverse_lazy won't execute until the value is needed.
    # # It is useful because it prevent Reverse Not Found exceptions when working with URLs that may not be immediately known.
    # # finally, reverse returns the str vs. reverse_lazy returns the object
    success_url = reverse_lazy("inventory:main")
    

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        form.do_action()
        print(form.cleaned_data)
        return super().form_valid(form)


from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from inventory.models import Car

class CarCreateView(CreateView):
    model = Car
    fields = ['brand', 'model', 'color', 'year'] # or "__all__"
    success_url = reverse_lazy("inventory:main")
    # template name should be <app>/<model>_form.html
    # e.g. car_form.html

    # optional
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.utils import timezone

class CarListView(LoginRequiredMixin, ListView):
    model = Car
    # optional
    paginate_by = 100  # if pagination is desired
    
    # template name should be <app>/<model>_list.html
    # e.g. car_list.html

    # optional
    # context_object_name = "car_list"

    # optional
    queryset = Car.objects.filter(brand__iexact="tesla")

    # optional
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


from django.views.generic.detail import DetailView

class CarDetailView(DetailView):
    model = Car


from django.views.generic.edit import UpdateView

class CarUpdateView(UpdateView):
    model = Car
    # optional
    fields = ['brand', 'model', 'color', 'year']
    success_url = reverse_lazy("inventory:car-list")

    # optional
    template_name_suffix = "_update_form"


from django.views.generic.edit import DeleteView

class CarDeleteView(DeleteView):
    model = Car
    success_url = reverse_lazy('inventory:car-list')

dealershop/inventory/templates/inventory/car_basic_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>

dealershop/inventory/templates/inventory/car_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

dealershop/inventory/templates/inventory/car_detail.html
<h1>{{ object.brand }}</h1>
<p>{{ object.model }}</p>
<p>{{ object.color }}</p>
<p>{{ object.year }}</p>
<a href="{% url "inventory:car-update" car.id %}">Update</a><br />
<a href="{% url "inventory:car-delete" car.id %}">Delete</a>

dealershop/inventory/templates/inventory/car_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>

dealershop/inventory/templates/inventory/car_list.html
<h1>Cars</h1>
<ul>
{{ now }}
{% for car in object_list %}
    <li><a href="{% url "inventory:car-detail" car.id %}">{{ car.brand }}: {{ car.model }} {{ car.color }} {{ car.year }}<a/></li>
{% empty %}
    <li>No cars yet.</li>
{% endfor %}
</ul>

dealershop/inventory/templates/inventory/car_update_form.html
<h1>Update</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update message">
</form>

dealershop/inventory/templates/inventory/fbv.html
You are logged in :D

dealershop/inventory/templates/inventory/main.html
<h1>Welcome to {{ name }}'s inventory main view</h1>
{% if user.is_authenticated %}
    <p>You are logged in as  {{ user.get_username }}</p>
    <p><a href="{% url 'account_logout' %}?next={{request.path}}">Log out</a></p>
{% else %}
    You are not logged in yet! Please login by clicking <a href="{% url 'account_login' %}?next={{request.path}}">here</a>
{% endif %}